# NumPy I

## Introduction

Selon [Wikipédia](https://fr.wikipedia.org/wiki/NumPy), `NumPy` est une bibliothèque pour langage de programmation `Python`, destinée à **manipuler** des matrices ou **tableaux multidimensionnels** ainsi que des **fonctions mathématiques** opérant sur ces tableaux. 

`NumPy` est la bibliothèque le plus utilisée en `Python` pour réaliser des opérations mathématiques. En fait, plusieurs bibliothèques populaires sont basées ou utilisent `NumPy`. Son usage est considéré comme faisant partie des connaissances de base à posséder pour plusieurs branches informatiques utilisant `Python`. Entre autre, elle permet :
 - une performance de calcul sans comparable avec l'usage simple de Python
 - une abstraction de haut niveau sur les opérations matricielles et mathématiques sous-jacentes
 - l'écriture de code plus compact, facile à lire, facile à maintenir et facile à déboguer.

`NumPy` est _de facto_ la bibliothèque la plus utilisée dans plusieurs branches scientifiques, technologiques et informatiques. D'ailleurs, certains projets ont été créé en Python pour utiliser `NumPy` et les bibliothèques dérivées, c'est tout dire! 

`NumPy` est largement inspirée de la technique de programmation réalisée par `Matlab`.

Il vaut la peine de mentionner que la documentation de `NumPy` est excellente!

## En bref

`NumPy` offre : 
 - information sur l'état des matrices
 - création de matrice
 - génération aléatoire
 - manipulation des matrices
 - un mécanisme d'indexation puissant
 - plusieurs fonctions et opérateurs mathématiques
 - vectorisation et _broadcasting_


## Installation

`pip install numpy`


## Références

 - [NumPy](https://numpy.org/) et [documentation officielle](https://numpy.org/doc/)
 - [Real Python](https://realpython.com/numpy-tutorial/)

---

## Mise en place

### Importation de la librairie

In [11]:
import numpy as np # l'alias np est généralement utilisé par convention

### Création de fonctions utilitaires pour ce document

In [12]:
def print_title(title, length = 80):
    print('-' * (length - len(title) - 1), ' ', title, sep='')
    
def print_result(statement_string):
    print_title(statement_string)
    print(eval(statement_string))
    
def print_demo(title, statement_string):
    print_title(title)
    print_result(statement_string)    

---

## `ndarray`
<div style="text-align: right"><a href="https://numpy.org/doc/stable/reference/arrays.ndarray.html">Documentation ndarray</a></div>

La classe `ndarray` est au coeur de la bibliothèque `NumPy`. C'est elle qui supporte les matrices multi-dimensionnelles. La nommenclature `ndarray` vient de _N-dimensional array_ pour **matrice à _N_ dimensions**.

Un objet `ndarray` est une structure de données décrite ainsi :
 - tableau à _N_ dimensions
 - les données sont contiguës en mémoire (linéairement organisé avec agencement flexible)
 - les données sont de types homogènes

### Création avec valeurs prédéterminées

Voilà 3 exemples de création d'objets `ndarray` avec des valeurs prédéterminées :
 - 1D, entiers 
 - 2D, entiers
 - 3D, réels

In [13]:
# Création d'une matrice 1D d'entiers de taille 6
data_1 = np.array([1, 2, 3, 4, 5, 6])

# Création d'une matrice 2D d'entiers de taille 2 x 3
data_2 = np.array([[1, 2, 3], 
                   [4, 5, 6]], np.uint16) # np.uint16 formalise le format à des entiers non signés de 16 bits

# Création d'une matrice 3D de réels de taille 2 x 2 x 3
data_3 = np.array([
                   [  [1., 1.5, 2.],
                      [3., 3.5, 4.] ],
                   
                   [  [9., 8.5, 8.],
                      [7., 6.5, 6.] ]  
                  ])

### Attributs

Plusieurs attributs décrivent la matrice :
 - `ndarray.dtype` : le type de données
 - `ndarray.ndim` : le nombre de dimensions
 - `ndarray.shape` : la forme de la matrice (un tuple décrivant la taille pour chacune des dimensions)
 - `ndarray.size` : le nombre d'éléments dans la matrice

In [14]:
def array_attributes(array_name):
    print_title(f'Attributs ndarray : { array_name }')
    print(f''' - dtype : {eval(array_name).dtype}
 - ndim : {eval(array_name).ndim}
 - shape : {eval(array_name).shape}
 - size : {eval(array_name).size}''')

array_attributes('data_1')
array_attributes('data_2')
array_attributes('data_3')

----------------------------------------------------- Attributs ndarray : data_1
 - dtype : int32
 - ndim : 1
 - shape : (6,)
 - size : 6
----------------------------------------------------- Attributs ndarray : data_2
 - dtype : uint16
 - ndim : 2
 - shape : (2, 3)
 - size : 6
----------------------------------------------------- Attributs ndarray : data_3
 - dtype : float64
 - ndim : 3
 - shape : (2, 2, 3)
 - size : 12


### Création avec valeurs uniformes

 - `empty` : une matrice sans initialisation de valeurs (!)
 - `identity` : une matrice 2D identité (matrice carrée remplie de 0 sauf pour la diagonale qui est à 1)
 - `zeros` : une matrice remplie de valeur 0
 - `ones` : une matrice remplie de valeur 1
 - `full` : une matrice remplie de la même valeur 

In [15]:
print_demo('empty 2D : 2 x 3', "np.empty((2, 3))")
print_demo('identity 2D : 3 x 3', "np.identity(3)")
print_demo('zeros 1D : 15', "np.zeros(15)")
print_demo('ones 2D : 2 x 10', "np.ones((2, 10))")
print_demo('full 4D avec -10 : 2 x 2 x 3 x 4', "np.full((2, 2, 3, 4), -10)")

--------------------------------------------------------------- empty 2D : 2 x 3
--------------------------------------------------------------- np.empty((2, 3))
[[2.33419537e-313 2.75859453e-313 3.18299369e-313]
 [3.60739285e-313 4.03179200e-313 4.45619116e-313]]
------------------------------------------------------------ identity 2D : 3 x 3
----------------------------------------------------------------- np.identity(3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
------------------------------------------------------------------ zeros 1D : 15
------------------------------------------------------------------- np.zeros(15)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
--------------------------------------------------------------- ones 2D : 2 x 10
--------------------------------------------------------------- np.ones((2, 10))
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
----------------------------------------------- full 4D avec -10 : 2 x 2 x 3 x 4
-----------------

  ### Création avec valeurs générées
 
 - `arange` : une série linéaire (décrite par itération)
 - `linspace` : une série linéaire (décrite par ses bornes et le nombre d'éléments)
 - `meshgrid` : retourne un ensemble de matrices à partir de plusieurs vecteurs
 - `fromfunction` : toutes les valeurs sont calculées à partir d'une fonction
 - `fromiter` : à partir d'un itérateur

In [16]:
print_demo('série de 0 à 9', "np.arange(10)")
print_demo('série de 0, 10, 20...100', "np.arange(0, 110, 10)")
print_demo('série de 11 données de 0 à 10', "np.linspace(0., 10., 11)")
print_demo('série de 5 données de 0 à 10', "np.linspace(0., 10., 5)")


def my_func_1(x, y): return x ** 2 + y ** 2
def my_func_2(x, y): return (x + 1) * 100 + (y + 1)

print_demo('x^2 + y^2', "np.fromfunction(my_func_1, (2, 5))")
print_demo('100 par ligne + 1 par colonne', "np.fromfunction(my_func_2, (2, 5))")


iter1 = [(i ** 2)/2 for i in range(10)]
iter2 = (4 * ((-1) ** k)/(2 * k + 1) for k in range(100000))

print_demo('itérateur : i^2/2', "np.fromiter(iter1, np.int32)")
print_demo('itérateur : série de pi', "np.fromiter(iter2, np.float32)")

----------------------------------------------------------------- série de 0 à 9
------------------------------------------------------------------ np.arange(10)
[0 1 2 3 4 5 6 7 8 9]
------------------------------------------------------- série de 0, 10, 20...100
---------------------------------------------------------- np.arange(0, 110, 10)
[  0  10  20  30  40  50  60  70  80  90 100]
-------------------------------------------------- série de 11 données de 0 à 10
------------------------------------------------------- np.linspace(0., 10., 11)
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
--------------------------------------------------- série de 5 données de 0 à 10
-------------------------------------------------------- np.linspace(0., 10., 5)
[ 0.   2.5  5.   7.5 10. ]
---------------------------------------------------------------------- x^2 + y^2
--------------------------------------------- np.fromfunction(my_func_1, (2, 5))
[[ 0.  1.  4.  9. 16.]
 [ 1.  2.  5. 10. 17.]]
--

  ### Création et manipulations aléatoires
  
Il existe deux approches pour la génération de nombres aléatoires avec `NumPy`. On présente ici l'approche moderne. L'idée est d'utiliser un objet `rng` (_Random Number Generator_) du module `numpy.random`. Cet objet offre plusieurs fonctions permettant de générer des nombres aélatoires selon plusieurs distributions statistiques.
 - `default_rng` : génère un objet `rng`
    - à même son constructeur, on peut définir le `seed`
 - de cet objet, plusieurs outils sont disponibles :
    - génération selon certaines distributions :
        - `rng.integers` : distribution uniforme d'entiers (minimum et maximum)
        - `rng.random` : distribution uniforme d'un réel entre 0 et 1
        - `rng.uniform` : distribution uniforme de réels (minimum et maximum)
        - `rng.normal` : distribution normale de réels (moyenne et écart type) 
         
    - il existe aussi plusieurs fonctions utilitaires intéressantes :
        - `rng.choice` : sélectionne aléatoirement certaines valeurs
        - `rng.shuffle` : mélange aléatoirement une matrice        

In [17]:
rng = np.random.default_rng(123)

print_demo('[0.0..1.0] : 2 x 3', 'rng.random((2,3))')
print_demo('[10..20] : 2 x 4', 'rng.integers(10, 20, (2,4))')
print_demo('[-5.0..5.0] : 2 x 4', 'rng.uniform(-5, 5, (2,4))')
print_demo('dist. normale : 2 x 3', 'rng.normal(10.0, 1.5, (2,3))')

test = np.arange(0, 110, 10)
print_result('test')
print_result('rng.choice(test, 3)')
rng.shuffle(test) # la fonction shuffle modifie le tableau original sans rien retourner
print_title('rng.shuffle(test)')
print(test)

------------------------------------------------------------- [0.0..1.0] : 2 x 3
-------------------------------------------------------------- rng.random((2,3))
[[0.68235186 0.05382102 0.22035987]
 [0.18437181 0.1759059  0.81209451]]
--------------------------------------------------------------- [10..20] : 2 x 4
---------------------------------------------------- rng.integers(10, 20, (2,4))
[[14 19 14 12]
 [17 18 18 18]]
------------------------------------------------------------ [-5.0..5.0] : 2 x 4
------------------------------------------------------ rng.uniform(-5, 5, (2,4))
[[ 0.12970455 -2.55035399  3.24241596 -2.86237037]
 [ 2.41467052  1.29940205  4.27407259 -2.68091811]]
---------------------------------------------------------- dist. normale : 2 x 3
--------------------------------------------------- rng.normal(10.0, 1.5, (2,3))
[[ 9.53230772 10.50665369  6.68879335]
 [11.24188216 12.31244559 11.69021019]]
------------------------------------------------------------------

## Interprétation

Quelques fonctions sont disponibles pour modifier la forme de la matrice :
 - `reshape` : défini une autre forme pour la matrice
 - `flatten` : retourne une matrice équivalente à 1 dimension

Il est aussi possible de retourner une matrice équivalente ayant un type différent :
 - `astype` : défini une autre forme pour la matrice


In [18]:
data = np.arange(24)
print_result('data')
print_result('data.reshape((2,12))')
print_result('data.reshape((12,2))')
print_result('data.reshape((4,6))')
print_result('data.reshape((6,4))')
print_result('data.reshape((2,3,4))')
print_result('data.reshape((2,2,2,3))')
print_result('data.reshape((2,12)).flatten()')

print_result('data.astype(np.float)')

--------------------------------------------------------------------------- data
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
----------------------------------------------------------- data.reshape((2,12))
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
----------------------------------------------------------- data.reshape((12,2))
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
------------------------------------------------------------ data.reshape((4,6))
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
------------------------------------------------------------ data.reshape((6,4))
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
---------------------------------------------------------- data.reshape((2,3,4))
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 1

## Indexation

Comme pour les listes de Python, plusieurs techniques d'indexation sont possibles :
 - accès direct : avec `[]`
 - _slicing_: avec `[ _from_ : _until_ : _step_ ]`
 - par sélection : avec `[[0,1]]`

In [19]:
data = np.arange(10, 22)
print_title('-')
print_result('data')
print_result('data[0]')
print_result('data[4:8]')
print_result('data[0:12:4]')
print_result('data[10:5:-1]')
print_result('data[[0,5,7]]')
print_result('data[[True, True, True, False, False, False, False, False, False, True, True, True]]')

data = np.arange(3 * 3 * 3).reshape(3,3,3)
print_title('-')
print_result('data')
print_result('data[1]')
print_result('data[2,1,0]')
print_result('data[0][1][2]')
print_result('data[0,:,:]')
print_result('data[:,0,:]')
print_result('data[:,:,0]')
print_result('data[[0,1,2],[0,1,2],[0,1,2]]')
print_result('data[0,0:2,0:2]')
print_result('data[0,...]')
print_result('data[...,0]')
print_result('data[:,:,0]')

data = np.arange(24).reshape(4,6)
print_title('-')
print_result('data')
print_result('data[3:0:-1,1:6:2]')

------------------------------------------------------------------------------ -
--------------------------------------------------------------------------- data
[10 11 12 13 14 15 16 17 18 19 20 21]
------------------------------------------------------------------------ data[0]
10
---------------------------------------------------------------------- data[4:8]
[14 15 16 17]
------------------------------------------------------------------- data[0:12:4]
[10 14 18]
------------------------------------------------------------------ data[10:5:-1]
[20 19 18 17 16]
------------------------------------------------------------------ data[[0,5,7]]
[10 15 17]
 data[[True, True, True, False, False, False, False, False, False, True, True, True]]
[10 11 12 19 20 21]
------------------------------------------------------------------------------ -
--------------------------------------------------------------------------- data
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [1

## Vectorisation

La vectorization (ou _vectorization_) est une technique qui consiste à réaliser certaines opérations élément par élément sur toute la matrice sans appels explicites de boucle de parcours. Les fonctions universelles et les opérateurs utilisent tous cette technique.

Avec cette approche, l'écriture du code est particulièrement compact et efficace. Un ensemble de règles doivent être respectées mais il est relativement intuitif d'utiliser cet outil incontournable.

La _vectorization_ est réalisée :
 - par :
    - les opérateurs :
    - les [fonctions universelles](https://numpy.org/doc/stable/reference/ufuncs.html)
 - avec ces conditions :
    - de matrices de tailles compatibles
    - entre une matrice et un scalaire (une seule valeur)

In [20]:
# exemples d'opérations mathématiques 

data1 = np.arange(12).reshape((3,4))
data2 = np.arange(10,22).reshape((3,4))

print_result('data1')
print_result('data2')
print_result('data1 + data2')
print_result('data1 * data2')
print_result('data1 + 100')
print_result('data1 / 100')
print_result('data1 ** 2')
print_result('data1 > 5')
print_result('data1[data1 > 5]')

-------------------------------------------------------------------------- data1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------------------------- data2
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
------------------------------------------------------------------ data1 + data2
[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
------------------------------------------------------------------ data1 * data2
[[  0  11  24  39]
 [ 56  75  96 119]
 [144 171 200 231]]
-------------------------------------------------------------------- data1 + 100
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]
-------------------------------------------------------------------- data1 / 100
[[0.   0.01 0.02 0.03]
 [0.04 0.05 0.06 0.07]
 [0.08 0.09 0.1  0.11]]
--------------------------------------------------------------------- data1 ** 2
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
---------------------------------------------------

In [21]:
# exemples de fonctions mathématiques 

data1 = np.arange(12).reshape((3,4))
data2 = np.arange(10,22).reshape((3,4))

print_result('data1')
print_result('data2')

print_result('np.sum(data1)') # on remarque que la somme est globale
print_result('np.sum(data1, axis=0)') # on remarque que la somme n'est que pour la 1re dimension
print_result('np.sum(data1, axis=1)') # on remarque que la somme n'est que pour la 2e dimension
print_result('np.min(data1)')
print_result('np.max(data1)')
print_result('np.mean(data1)')
print_result('np.median(data1)')
print_result('np.std(data1)')
print_result('np.sum((data1 - data2)**2, axis=0)**0.5')

print_result('np.degrees(np.cos(data1 / (2. * np.pi)))')
print_result('np.round(data1 ** 2.37)')



-------------------------------------------------------------------------- data1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------------------------- data2
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
------------------------------------------------------------------ np.sum(data1)
66
---------------------------------------------------------- np.sum(data1, axis=0)
[12 15 18 21]
---------------------------------------------------------- np.sum(data1, axis=1)
[ 6 22 38]
------------------------------------------------------------------ np.min(data1)
0
------------------------------------------------------------------ np.max(data1)
11
----------------------------------------------------------------- np.mean(data1)
5.5
--------------------------------------------------------------- np.median(data1)
5.5
------------------------------------------------------------------ np.std(data1)
3.452052529534663
---------------------------------------

## _Broadcasting_

Le _broadcasting_ est une technique issue de la vectorisation applicable à des matrices de tailles différentes. Encore une fois, la technique vise à effectuer des opérations éléments par éléments sans spécifier explicitement les parcours.

Quelques règles doivent être respectées pour que le _broadcasting_ s'applique. Prenons l'exemple de matrices 2d :
 - les tailles sont égales (vectorisation directe)
 - l'une des tailles est égale à 1
 
Dans le 2e cas, l'opération est alors projetée sur l'axe de taille 1.

In [22]:
data1 = np.arange(12).reshape((3,4))
data2 = np.arange(0,40,10)
data3 = np.arange(0,30,10).reshape(3,1)

print_result('data1')
print_result('data2')
print_result('data3')

print_result('data1 + data2') 
print_result('data1 + data3')
print_result('data2 + data3')

-------------------------------------------------------------------------- data1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------------------------- data2
[ 0 10 20 30]
-------------------------------------------------------------------------- data3
[[ 0]
 [10]
 [20]]
------------------------------------------------------------------ data1 + data2
[[ 0 11 22 33]
 [ 4 15 26 37]
 [ 8 19 30 41]]
------------------------------------------------------------------ data1 + data3
[[ 0  1  2  3]
 [14 15 16 17]
 [28 29 30 31]]
------------------------------------------------------------------ data2 + data3
[[ 0 10 20 30]
 [10 20 30 40]
 [20 30 40 50]]
